In [1]:
from numpy import random
from numpy import abs

x = random.sample((10,3))
print(x,'\n')
ind = abs(x - 0.5).argmin(axis = 1)
i = 0
while i < 10:
    print(x[i][ind[i]])
    i += 1
    

[[0.14460897 0.99713468 0.5495361 ]
 [0.51260892 0.89074771 0.41895686]
 [0.55273875 0.38292434 0.27627431]
 [0.17388905 0.81691827 0.68403547]
 [0.33293419 0.39900483 0.44822244]
 [0.94275296 0.25430488 0.9412908 ]
 [0.35403767 0.30994906 0.56902711]
 [0.59733201 0.31415514 0.28872429]
 [0.87748143 0.37938577 0.18019111]
 [0.82108702 0.98007028 0.69651254]] 

0.5495361044230523
0.5126089231272767
0.5527387468690259
0.6840354698238585
0.4482224433759424
0.25430488446012167
0.5690271140520722
0.5973320107040682
0.37938577116010497
0.6965125429522057


In [2]:
from numpy import sum
from numpy import random

x = 10*random.random((6,6))
print(x)
ind = x.argmin(axis = 0)
i = 0
while i < 6:
    print('\n', sum(x[i])/x[ind[i]][i])
    i += 1

[[6.95925358 0.69809246 3.02852488 0.92471136 3.78691966 4.04340204]
 [2.47496645 3.76675035 4.31918143 5.16347177 5.38703632 2.8252539 ]
 [1.92576641 4.0665497  1.07508087 4.24717337 0.46015641 6.99601013]
 [3.2456436  4.84972487 8.49356655 4.25898232 7.15773769 4.45272459]
 [0.6386606  2.93649801 2.18928141 7.87610352 6.76141049 2.72261677]
 [7.96590949 7.5649893  5.70481326 5.75342846 0.91201772 6.71597379]]

 30.440117914125235

 34.28866734941003

 17.459837137567533

 35.101093324063754

 50.25371904945989

 12.714654646529217


In [19]:
from numpy import array
from numpy import random

def max_after_zero(x):
    length = x.shape[0]
    x = x.tolist()
    i = 0
    m = 0
    while i < length:
        try:
            i = x.index(0, i, length) + 1
        except Exception as info:
            print(info)
            m = -1
            break
        if i == length :
            break
        if m < x[i]: 
            m = x[i]
    if m > 0:        
        print(m)

if __name__ == '__main__':
    x = array([6, 2, 0, 3, 0, 0, 5, 7, 0])
    z = random.sample((5))
    print(z)
    max_after_zero(z)
    print(x)
    max_after_zero(x)



[0.71901285 0.39346096 0.2313302  0.16009484 0.12629887]
0 is not in list
[6 2 0 3 0 0 5 7 0]
5


In [21]:
import numpy

x = numpy.ones(10)
i = numpy.array([0, 1, 2, 3, 5, 5, 5, 8])

print(x)
j = 0
while j < 8:
    x[i[j]] += 1
    j += 1
print(x)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


In [1]:
from numpy import arange

n = 10
a = arange(n*n).reshape(n,n)
b = {}
i = 0
ii = 0
while i < 2*n - 1:
    b[i] = []
    i += 1
while ii < n:
    j = 0
    while j < n:
        b.get(ii + j).append(a[ii][j])
        j += 1
    ii += 1
print(b)

{0: [0], 1: [1, 10], 2: [2, 11, 20], 3: [3, 12, 21, 30], 4: [4, 13, 22, 31, 40], 5: [5, 14, 23, 32, 41, 50], 6: [6, 15, 24, 33, 42, 51, 60], 7: [7, 16, 25, 34, 43, 52, 61, 70], 8: [8, 17, 26, 35, 44, 53, 62, 71, 80], 9: [9, 18, 27, 36, 45, 54, 63, 72, 81, 90], 10: [19, 28, 37, 46, 55, 64, 73, 82, 91], 11: [29, 38, 47, 56, 65, 74, 83, 92], 12: [39, 48, 57, 66, 75, 84, 93], 13: [49, 58, 67, 76, 85, 94], 14: [59, 68, 77, 86, 95], 15: [69, 78, 87, 96], 16: [79, 88, 97], 17: [89, 98], 18: [99]}
